### ISSUE TITLE
Failing class directives due to breathe_default_project

### ISSUE THREAD

**Issue by markhh80** [mithro/sphinx-contrib-mithro#1]
Hello,

thanks for contributing the multi project feature! 

I tested it today with two sample projects (api1, api2) but I have issues with broken references when browsing the documentation. The problem is caused by directives like 'doxygenclass' to assume the breathe default project to be source of a class when  :project: (...) is not explicitley added.

Unfortunately, exhale does not add the :project: directives when generating the API documentation. You can configure exhale to add those again via overriding ""specificationsForKind" and injecting it via exhale_args (source: exhale documentation), but this does not provide a fix as it just adds ":project:" without the actual project as value (I got this all working so I assume I am using it correctly).

My project structure is:

my_sphinx_doc
  /source
     /api1/index.rst
             ... files generated by exhale
     /api2/index.rst
            ... files generated by exhale
  conf.py
  index.rst (refer to api1/index, api2/index))
  (...)

conf.py:
breathe_default_project = "api1"
-> api2 references fail

breathe_default_project = "api2"
-> api1 references fail

Am I missing something here? I assume you tested the feature and had a working example?

Thanks and regards,
Mark

**Comment by mithro** [comment]
I believe upstream now has native support for this and you no longer need my extension?

**Comment by mithro** [comment]
See discussion at https://github.com/svenevs/exhale/issues/27

**Comment by markhh80** [comment]
Ah I see, thank you! (closed)
